import os
RESTCLIENTS_CANVAS_DAO_CLASS='Live'
RESTCLIENTS_CANVAS_HOST = 'https://canvas.uw.edu'
RESTCLIENTS_CANVAS_OAUTH_BEARER = os.environ.get('CANVAS_API_TOKEN')
RESTCLIENTS_CANVAS_ACCOUNT_ID = 1
RESTCLIENTS_CANVAS_USER_AGENT = 'CCUWRosterSyncService/1.0'
RESTCLIENTS_CA_BUNDLE = '/etc/ssl/cert.pem'

